config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, except: [:edit, :update, :destroy] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian'] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, numericality: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @categories = ['chinese', 'italian', 'japanese', 'french', 'belgian']
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show
    # one particular restaurant (details-page)
    @restaurant = Restaurant.find(params[:id])
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>

<div class="outer-card">
  <% @restaurants.each do |restaurant| %>
    <div class="card">
<!--       <div>
        <img src="https://source.unsplash.com/random/150x150">
      </div> -->
      <div>
        <h5><strong><%= restaurant.name%></strong></h5>
        <p><%= restaurant.address %></p>
        <p><%= restaurant.category.capitalize %></p>
        <p><%= link_to "Show", restaurant_path(restaurant), class:"btn btn-outline-primary btn-sm rounded my-1" %></p>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "Add a new Restaurant", new_restaurant_path, class:"btn btn-primary rounded" %>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<p>Find me in app/views/restaurants/new.html.erb</p>

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category, :collection => @categories %>
  <%= f.input :phone_number %>
  <%= f.button :submit, class: "btn btn-primary rounded"%>
<% end %>

app/views/restaurants/show.html.erb
<h1 class="py-2"><%= @restaurant.name %></h1>
<hr>

<div class="details">
  <p>Located in: <%= @restaurant.address %></p>
  <p>Phone no.: <%= @restaurant.phone_number %></p>
  <p>Cuisine: <%= @restaurant.category.capitalize %></p>
</div>

<div class="outer-card">
  <% @restaurant.reviews.each do |review| %>
    <div class="card">
      <p><i class="fas fa-star"></i>: <%= review.rating %>/5</p>
      <p><%= review.content %></p>
    </div>
  <% end %>
</div>

<p><%= link_to "Add a review", new_restaurant_review_path(@restaurant), class:"btn btn-primary btn-sm rounded" %></p>
<p><%= link_to "Back to all restaurants", restaurants_path, class:"btn btn-primary btn-sm rounded" %></p>

<hr>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.button :submit, class: "btn btn-primary rounded"%>
<% end %>